#+TITLE: James Fletcher's Emacs configuration
#+AUTHOR: James Fletcher

* Configuration
*** User info
Configure my name and email address properly.
#+BEGIN_SRC emacs-lisp
(setq user-full-name "James Fletcher"
      user-mail-address "m@jef.me.uk")
#+END_SRC
*** Common lisp for Emacs
(require 'cl)
* Package management
Since Emacs 24, Emacs includes the Emacs Lisp Package Archive (ELPA)
by default. This provides a nice way to install additional
packages. Since the default package archive doesn't include everything
necessary, the marmalade, and melpa repositories are also added. 
*** Default packages
Define a list of default packages that I regularly require.
#+BEGIN_SRC emacs-lisp
(defvar jamesf/packages '(auto-complete
                          autopair
                          deft
                          erlang
                          feature-mode
                          flycheck
                          gist
                          go-mode
                          graphviz-dot-mode
                          haml-mode
                          haskell-mode
                          htmlize
                          magit
                          markdown-mode
                          marmalade
                          nodejs-repl
                          o-blog
                          paredit
                          restclient
                          smex
                          sml-mode
                          web-mode
                          writegood-mode
                          yaml-mode)
  "Default packages")
#+END_SRC
*** Install default package
Check to see if default packages are available at boot time and
install them if not.
#+BEGIN_SRC emacs-lisp
(defun jamesf/packages-installed-p ()
  (loop for pkg in jamesf/packages
        when (not (package-installed-p pkg)) do (return nil)
        finally (return t)))

(unless (jamesf/packages-installed-p)
  (message "%s" "Refreshing package database...")
  (package-refresh-contents)
  (dolist (pkg jamesf/packages)
    (when (not (package-installed-p pkg))
      (package-install pkg))))
#+END_SRC
* Start-up options
I want to skip straight to the scratch buffer. This turns off the
splash screen and puts me straight into the scratch buffer. I don't
really care to have anything in there either, so turn off the message
while we're at it. Since I end up using org-mode most of the time, set
the default mode accordingly. 
#+BEGIN_SRC emacs-lisp
(setq inhibit-splash-screen t
      initial-scratch-message nil
      initial-major-mode 'org-mode)
#+END_SRC
** Tool bars
#+BEGIN_SRC emacs-lisp
(scroll-bar-mode -1)
(tool-bar-mode -1)
(menu-bar-mode -1)
#+END_SRC
** Marking text
#+BEGIN_SRC emacs-lisp
(delete-selection-mode t)
(transient-mark-mode t)
(setq x-select-enable-clipboard t)
#+END_SRC
** Display settings
#+BEGIN_SRC emacs-lisp
(when window-system
  (setq frame-title-format '(buffer-file-name "%f" ("%b"))))

(setq-default indicate-empty-lines t)
(when (not indicate-empty-lines)
  (toggle-indicate-empty-lines))
#+END_SRC
** Indentation
#+BEGIN_SRC emacs-lisp
(setq tab-width 2
      indent-tabs-mode nil)
#+END_SRC
** Backup files
No thx.
#+BEGIN_SRC emacs-lisp
(setq make-backup-files nil)
#+END_SRC
** Yes and no alias.
Sane default
#+BEGIN_SRC emacs-lisp
  (defalias 'yes-or-no-p 'y-or-n-p)
#+END_SRC
** Misc
Other stuff
#+BEGIN_SRC emacs-lisp
(setq echo-keystrokes 0.1
      use-dialog-box nil
      visible-bell t)
(show-paren-mode t)
#+END_SRC
* Org
Org mode rocks. 
** Settings
#+BEGIN_SRC emacs-lisp
(setq org-log-done t
      org-todo-keywords '((sequence "TODO" "INPROGRESS" "DONE"))
      org-todo-keyword-faces '(("INPROGRESS" . (:foreground "blue" :weight bold))))
(add-hook 'org-mode-hook
          (lambda ()
            (flyspell-mode)))
(add-hook 'org-mode-hook
          (lambda ()
            (writegood-mode)))
#+END_SRC
** org-agenda
First, create the global binding for org-agenda. This allows it to be quickly accessed. The agenda view requires that org files be added to it. The fletcher.org and todo.org files are my daily files for review. I have a habit to plan the next day. I do this by assessing my calendar and my list of todo items. If a todo item is already scheduled or has a deadline, don't show it in the global todo list. 
#+BEGIN_SRC emacs-lisp
  (global-set-key (kbd "C-c a") 'org-agenda)
  (setq org-agenda-show-log t
        org-agenda-todo-ignore-scheduled t
        org-agenda-todo-ignore-deadlines t)
  (setq org-directory "~/Private/org")
  (setq org-default-notes-file "~/Private/org/organizer.org")
  (setq org-agenda-files (list "~/Private/org/fletcher.org"
                               "~/Private/org/todo.org"))
#+END_SRC
** org-babel
org-babel is a feature inside of org-mode that makes this document possible. It allows for embedding languages inside of an org-mode document with all the proper font-locking. It also allows you to extract and execute code. It isn't aware of Clojure by default, so the following sets that up. 
#+BEGIN_SRC emacs-lisp
(require 'ob)

(org-babel-do-load-languages
 'org-babel-load-languages
 '((sh . t)
   (ditaa . t)
   (plantuml . t)
   (dot . t)
   (ruby . t)))

(add-to-list 'org-src-lang-modes (quote ("dot". graphviz-dot)))
(add-to-list 'org-src-lang-modes (quote ("plantuml" . fundamental)))
(add-to-list 'org-babel-tangle-lang-exts '("clojure" . "clj"))

(defvar org-babel-default-header-args:clojure
  '((:results . "silent") (:tangle . "yes")))

(defun org-babel-execute:clojure (body params)
  (lisp-eval-string body)
  "Done!")

(provide 'ob-clojure)

(setq org-src-fontify-natively t
      org-confirm-babel-evaluate nil)

(add-hook 'org-babel-after-execute-hook (lambda ()
                                          (condition-case nil
                                              (org-display-inline-images)
                                            (error nil)))
          'append)

#+END_SRC
** org-abbrev
#+BEGIN_SRC emacs-lisp
(add-hook 'org-mode-hook (lambda () (abbrev-mode 1)))

(define-skeleton skel-org-block-elisp
  "Insert an emacs-lisp block"
  ""
  "#+begin_src emacs-lisp\n"
  _ - \n
  "#+end_src\n")

(define-abbrev org-mode-abbrev-table "selisp" "" 'skel-org-block-elisp)

(define-skeleton skel-header-block
  "Creates my default header"
  ""
  "#+TITLE: " str "\n"
  "#+AUTHOR: James Fletcher\n"
  "#+EMAIL: m@jef.me.uk\n"
  "#+OPTIONS: toc:3 num:nil\n"
  "#+STYLE: <link rel=\"stylesheet\" type=\"text/css\" href=\"http://thomasf.github.io/solarized-css/solarized-light.min.css\" />\n")

(define-abbrev org-mode-abbrev-table "sheader" "" 'skel-header-block)
#+END_SRC
** ditaa
#+BEGIN_SRC emacs-lisp
  (setq org-ditaa-jar-path "~/Private/bin/ditaa.jar")
#+END_SRC
** Plant UML
#+BEGIN_SRC emacs-lisp
  (setq org-plantuml-jar-path "~/Private/bin/plantuml.jar")
#+END_SRC
** deft
deft provides random note taking with history and searching. Since I use org-mode for everything else, I turn that on as the default mode for deft and put the files in Dropbox.
#+BEGIN_SRC emacs-lisp
(setq deft-directory "~/Private/org/deft")
(setq deft-use-filename-as-title t)
(setq deft-extension "org")
(setq deft-text-mode 'org-mode)
#+END_SRC
** Smex
#+BEGIN_SRC emacs-lisp
(setq smex-save-file (expand-file-name ".smex-items" user-emacs-directory))
(smex-initialize)
(global-set-key (kbd "M-x") 'smex)
(global-set-key (kbd "M-X") 'smex-major-mode-commands)
#+END_SRC
** Ido
#+BEGIN_SRC emacs-lisp
(ido-mode t)
(setq ido-enable-flex-matching t
      ido-use-virtual-buffers t)
#+END_SRC
** Misc
#+BEGIN_SRC emacs-lisp
  (setq column-number-mode t
        backup-directory-alist `((".*" . ,temporary-file-directory))
        auto-save-file-name-transforms `((".*" ,temporary-file-directory t)))
#+END_SRC
** autopair
autopair mode
#+BEGIN_SRC emacs-lisp
(require 'autopair)
#+END_SRC
** Auto-complete
#+BEGIN_SRC emacs-lisp
  (require 'auto-complete-config)
  (ac-config-default)
#+END_SRC
** Flyspell
#+BEGIN_SRC emacs-lisp
  (setq flyspell-issue-welcome-flag nil)
  (setq-default ispell-program-name "/usr/bin/aspell")
  (setq ispell-local-dictionary "british")
  (setq-default ispell-list-command "list")
#+END_SRC
** Colors
#+BEGIN_SRC emacs-lisp
  (load-theme 'leuven t)
  (set-default-font "Terminus-10")
#+END_SRC
* Extra functionality
Include extra functionality provided by emacs24-starter-kit.
#+BEGIN_SRC emacs-lisp
(defvar starter-kit-extras '("haskell" "js" "misc-recommended" "org" "perl"))
(mapcar 'starter-kit-load starter-kit-extras)
;; (starter-kit-load "haskell")
#+END_SRC
